//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Stock = new HashSet<Stock>();
        }
    
        public int IdProducto { get; set; }
        public string Tipo { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> idColor { get; set; }
        public Nullable<int> idTalle { get; set; }
        public Nullable<int> idMarca { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Talle Talle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
